[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino

monitor_speed = 115200
upload_speed = 460800

lib_deps = 
    olikraus/U8g2@^2.35.0
    tzapu/WiFiManager@^2.0.17-rc.2
    bblanchon/ArduinoJson@^7.0.0